# fly.toml app configuration file generated for spring-camp on 2025-03-26T01:05:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spring-camp'
primary_region = 'sea'

[deploy]
  release_command = "rake db:migrate && rake db:seed"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
