ruby '3.1.6'
source 'https://rubygems.org'

gem 'activerecord', '~> 6.1'
gem 'bcrypt', '~> 3.1'
gem 'cloudinary', '~> 1.24'
gem 'dotenv', '~> 2.7'
gem 'pg', '~> 1.2'
gem 'rake', '~> 13.2'
gem 'sinatra', '~> 2.2'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sinatra-contrib', '~> 2.2'
gem 'webrick', '~> 1.8'
gem 'httparty'